/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        ink: 'var(--color-ink)',
        'on-primary': 'var(--color-on-primary)',
        canvas: 'var(--color-canvas)',
        surface: 'var(--color-canvas)',
        'soft-cloud': 'var(--color-soft-cloud)',
        charcoal: 'var(--color-charcoal)',
        mute: 'var(--color-mute)',
        stone: 'var(--color-stone)',
        hairline: 'var(--color-hairline)',
        'hairline-soft': 'var(--color-hairline-soft)',
        success: 'var(--color-success)',
        error: 'var(--color-error)',
        warning: 'var(--color-warning)',
      },
      borderRadius: {
        none: '0px',
        sm: '18px',
        DEFAULT: '24px',
        lg: '30px',
        full: '9999px',
      },
      spacing: {
        xxs: '2px',
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '18px',
        xl: '24px',
        xxl: '30px',
        section: '48px',
      },
      fontFamily: {
        display: ['Anton', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-campaign': ['64px', { lineHeight: '0.9', fontWeight: '500' }],
        'heading-xl': ['32px', { lineHeight: '1.2', fontWeight: '500' }],
        'heading-lg': ['24px', { lineHeight: '1.2', fontWeight: '500' }],
        'heading-md': ['16px', { lineHeight: '1.75', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-strong': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
        'button-md': ['16px', { lineHeight: '1.5', fontWeight: '500' }],
        'caption-md': ['14px', { lineHeight: '1.5', fontWeight: '500' }],
        'caption-sm': ['12px', { lineHeight: '1.5', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
